services:
  - type: web
    name: meetloom
    env: node
    buildCommand: npm install
    startCommand: npm start
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: SESSION_SECRET
        generateValue: true
      - key: CLIENT_ID
        sync: false
      - key: CLIENT_SECRET
        sync: false
      - key: REDIRECT_URI
        sync: false
